import { Group } from './Group.js';
import type { ExtendedManifestEntry } from './AutoUpgrade.ts';
export { getAllGroups, getGroupsByOrder } from './GroupRegistry.js';
export declare const GENERATED_GROUP_PREFIX = "data:,//GE3/generated";
export declare const GAPID_GROUP_PREFIX = "data:,//GE3/gapid";
export declare function loadLibrary(): Promise<void>;
export declare function loadFromStoredGroups(storedGroupsJSON: unknown): void;
export declare function deleteGroups(groups: Group[]): void;
export declare function getGroupByRef(url: string): Maybe<Group>;
export declare function loadFromPageURL(): Promise<Group>;
export declare function saveGroup(group: Maybe<Group>): void;
type LibraryUpdate = {
    source: 'library';
    created: string[];
    updated: string[];
    deleted: string[];
};
export declare function isLibraryUpdate(message: unknown): message is LibraryUpdate;
export declare function saveLibrary(): Promise<unknown>;
export declare function updateGroups(manifest: ReadonlyArray<string | ExtendedManifestEntry>): Promise<void>;
